### ISSUE TITLE
14.0-14.1 still incompatible on A11 and above

### ISSUE THREAD

**Issue by Bailijiushi** [m1stadev/futurerestore#20]
hello~i am wondering when futurerestore will be compatible with A11 (iphone 8 plus) for 14.0-14.1. 
I have updated my iphone 8 plus to 14.6 and right now I feel very desperate because of the bad battery draining and bad performance. I really want to downgrade to an old version like 14.01 or 14.1 but it always stops with the notice "unable to receive message from FDR" and cannot go on. 
**Really appreciate the effort you've made always.**

**Comment by Tanbeer191** [comment]
there's no point opening a github issue for something that won't be fixed. SEP is likely incompatible, you can stop waiting.

**Comment by Cryptiiiic** [comment]
false, 14.x SEPOS is compatible down to 13.4. Apple added mitigations or a new feature set in 14.3 for a11-a14 that breaks SEP SKS skgs when going below 14.3. I've been looking into a fix or workaround for many months now. @Bailijiushi @Tanbeer191

**Comment by tolikes** [comment]
> false, 14.x SEPOS is compatible down to 13.4. Apple added mitigations or a new feature set in 14.3 for a11-a14 that breaks SEP SKS skgs when going below 14.3. I've been looking into a fix or workaround for many months now. @Bailijiushi @Tanbeer191

you mean i can downgrade my iphone 11 to ios 13.7 version?

**Comment by Cryptiiiic** [comment]
<img width="165" alt="image" src="https://user-images.githubusercontent.com/27748705/120615142-d1984100-c40c-11eb-9a3d-2b91077e3a25.png">
@tolikes

**Comment by dabezt31** [comment]
![33F861B6-3514-4C27-B33B-A0D356A1AB08](https://user-images.githubusercontent.com/48022799/120615391-e7cfec80-c460-11eb-888e-74d5e1fc50a2.png)
@Bailijiushi

**Comment by Tanbeer191** [comment]
this is why you’re better off giving people an ultimatum rather than trying to explain something to them

**Comment by Bailijiushi** [comment]
> false, 14.x SEPOS is compatible down to 13.4. Apple added mitigations or a new feature set in 14.3 for a11-a14 that breaks SEP SKS skgs when going below 14.3. I've been looking into a fix or workaround for many months now. @Bailijiushi @Tanbeer191

many thanks for your prompt and specific reply. I will keep waiting for good news and hope it will finally come. /salute
